version: '3.1'

services:

  db:
    image: postgres:14.1
    restart: always
    container_name: dend_1_sparkify_db
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - "5432:5432"
